# Generated by Django 2.2.6 on 2019-10-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evento')),
                ('titulo', models.CharField(max_length=200)),
                ('f_inicio', models.DateTimeField()),
                ('f_finalizacion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
