# Generated by Django 2.2.6 on 2019-10-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriante',
            name='delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
