# Generated by Django 2.2.6 on 2019-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriante', '0002_auto_20191017_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriante',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
